# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('grado', models.CharField(max_length=15)),
                ('jornada', models.CharField(max_length=30)),
                ('estado_activo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologyTest.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('sitio_web', models.CharField(max_length=30)),
                ('estado_activo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjer\xeda')], default='CC', max_length=5, verbose_name='Tipo de documento')),
                ('Nro_dodocumento', models.CharField(max_length=25, verbose_name='Documento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Lgtbi')], max_length=2, verbose_name='G\xe9nero')),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('PSI', 'Psic\xf3logo'), ('EST', 'Estudiante')], default='EST', max_length=5, verbose_name='Rol')),
                ('estado_activo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologyTest.Grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologyTest.Perfil_usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='institucion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologyTest.Perfil_usuario', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='grupo_institucion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologyTest.Institucion'),
        ),
        migrations.AddField(
            model_name='grupo_institucion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologyTest.Perfil_usuario', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologyTest.Perfil_usuario', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologyTest.Grupo'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologyTest.Perfil_usuario', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='admin',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologyTest.Institucion'),
        ),
        migrations.AddField(
            model_name='admin',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologyTest.Perfil_usuario', verbose_name='Usuario'),
        ),
    ]
