# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologyTest', '0004_auto_20160928_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjer\xeda')], default='CC', max_length=5, verbose_name='Tipo de documento')),
                ('documento', models.CharField(max_length=25, verbose_name='Documento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Lgtbi')], max_length=2, verbose_name='G\xe9nero')),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=50)),
                ('grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('institucion', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('PSI', 'Psic\xf3logo'), ('EST', 'Estudiante')], default='ADMIN', max_length=5, verbose_name='Rol')),
                ('estado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_psicologo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjer\xeda')], default='CC', max_length=5, verbose_name='Tipo de documento')),
                ('documento', models.CharField(max_length=25, verbose_name='Documento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Lgtbi')], max_length=2, verbose_name='G\xe9nero')),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('PSI', 'Psic\xf3logo'), ('EST', 'Estudiante')], default='ADMIN', max_length=5, verbose_name='Rol')),
                ('estado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil_admin',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='perfil_admin',
            name='institucion',
        ),
    ]
