# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologyTest', '0006_auto_20160928_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('grado', models.CharField(max_length=15)),
                ('jornada', models.CharField(max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
